"""Initial

Revision ID: 2d6a63dcc8d7
Revises: 
Create Date: 2026-07-25 17:04:35.308142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6a63dcc8d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins'))
    )
    op.create_index(op.f('ix_admins_created_at'), 'admins', ['created_at'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('contact_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'READ', 'REPLIED', name='contactstatus'), server_default='NEW', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_requests'))
    )
    op.create_index(op.f('ix_contact_requests_company'), 'contact_requests', ['company'], unique=False)
    op.create_index(op.f('ix_contact_requests_created_at'), 'contact_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_requests_email'), 'contact_requests', ['email'], unique=False)
    op.create_index(op.f('ix_contact_requests_status'), 'contact_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_requests_status'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_email'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_created_at'), table_name='contact_requests')
    op.drop_index(op.f('ix_contact_requests_company'), table_name='contact_requests')
    op.drop_table('contact_requests')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_created_at'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
