"""create meeting_requests table

Revision ID: fc53b0c42c95
Revises: 2d6a63dcc8d7
Create Date: 2026-07-30 16:16:43.645798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc53b0c42c95'
down_revision: Union[str, Sequence[str], None] = '2d6a63dcc8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='meeting_request_status', create_constraint=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_requests'))
    )
    op.create_index(op.f('ix_meeting_requests_business_email'), 'meeting_requests', ['business_email'], unique=False)
    op.create_index(op.f('ix_meeting_requests_created_at'), 'meeting_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_meeting_requests_id'), 'meeting_requests', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_requests_meeting_date'), 'meeting_requests', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meeting_requests_status'), 'meeting_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_requests_status'), table_name='meeting_requests')
    op.drop_index(op.f('ix_meeting_requests_meeting_date'), table_name='meeting_requests')
    op.drop_index(op.f('ix_meeting_requests_id'), table_name='meeting_requests')
    op.drop_index(op.f('ix_meeting_requests_created_at'), table_name='meeting_requests')
    op.drop_index(op.f('ix_meeting_requests_business_email'), table_name='meeting_requests')
    op.drop_table('meeting_requests')
    # ### end Alembic commands ###
